# =============================================================================
# This file proves deployment on Alibaba Cloud services for the Qwen Cloud
# Hackathon.
#
# It provisions the full Memoria backend stack on Alibaba Cloud (Alicloud):
#   - ECS instance (Ubuntu 22.04) running the FastAPI app in Docker
#   - ApsaraDB RDS for PostgreSQL (pgvector-capable, PG 16)
#   - ApsaraDB for Redis (KVStore)
#   - VPC / VSwitch / Security Group (ports 22 + 8000 open)
#
# It is intentionally not applied in CI; it is proof-of-architecture for judges.
# Passwords are generated by Terraform (random_password) and never hard-coded.
# =============================================================================

terraform {
  required_version = ">= 1.3.0"

  required_providers {
    alicloud = {
      source  = "aliyun/alicloud"
      version = "~> 1.220"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
  }
}

# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------
variable "region" {
  description = "Alibaba Cloud region to deploy into."
  type        = string
  default     = "ap-southeast-1" # Singapore (international)
}

variable "dashscope_api_key" {
  description = "DashScope (Qwen) API key, injected into the backend container."
  type        = string
  sensitive   = true
  default     = ""
}

variable "backend_image" {
  description = "Pre-built backend container image (assumed available in a registry)."
  type        = string
  default     = "registry.cn-hangzhou.aliyuncs.com/memoria/backend:latest"
}

variable "ecs_instance_type" {
  description = "ECS instance type for the app server."
  type        = string
  default     = "ecs.e-c1m1.large"
}

# -----------------------------------------------------------------------------
# Provider
# -----------------------------------------------------------------------------
provider "alicloud" {
  region = var.region
}

# -----------------------------------------------------------------------------
# Generated credentials (never hard-coded)
# -----------------------------------------------------------------------------
resource "random_password" "db" {
  length  = 20
  special = false
}

resource "random_password" "redis" {
  length  = 20
  special = false
}

# -----------------------------------------------------------------------------
# Lookups: availability zone + Ubuntu 22.04 image
# -----------------------------------------------------------------------------
data "alicloud_zones" "default" {
  available_resource_creation = "Instance"
}

data "alicloud_images" "ubuntu" {
  owners      = "system"
  most_recent = true
  name_regex  = "^ubuntu_22_04_x64.*"
}

# -----------------------------------------------------------------------------
# Networking: VPC + VSwitch + Security Group (open ports 22 and 8000)
# -----------------------------------------------------------------------------
resource "alicloud_vpc" "this" {
  vpc_name   = "memoria-vpc"
  cidr_block = "10.0.0.0/16"
}

resource "alicloud_vswitch" "this" {
  vswitch_name = "memoria-vswitch"
  vpc_id       = alicloud_vpc.this.id
  cidr_block   = "10.0.1.0/24"
  zone_id      = data.alicloud_zones.default.zones[0].id
}

resource "alicloud_security_group" "this" {
  security_group_name = "memoria-sg"
  vpc_id              = alicloud_vpc.this.id
}

resource "alicloud_security_group_rule" "ssh" {
  type              = "ingress"
  ip_protocol       = "tcp"
  nic_type          = "intranet"
  policy            = "accept"
  port_range        = "22/22"
  priority          = 1
  security_group_id = alicloud_security_group.this.id
  cidr_ip           = "0.0.0.0/0"
}

resource "alicloud_security_group_rule" "app" {
  type              = "ingress"
  ip_protocol       = "tcp"
  nic_type          = "intranet"
  policy            = "accept"
  port_range        = "8000/8000"
  priority          = 1
  security_group_id = alicloud_security_group.this.id
  cidr_ip           = "0.0.0.0/0"
}

# -----------------------------------------------------------------------------
# ApsaraDB RDS for PostgreSQL (pgvector-capable). Enable the extension with
# `CREATE EXTENSION IF NOT EXISTS vector;` after the instance is up.
# -----------------------------------------------------------------------------
resource "alicloud_db_instance" "postgres" {
  engine           = "PostgreSQL"
  engine_version   = "16.0"
  instance_type    = "pg.n2.2c.1m" # small dev-tier class; adjust per region
  instance_storage = 20
  vswitch_id       = alicloud_vswitch.this.id
  instance_name    = "memoria-postgres"
  security_ips     = ["10.0.0.0/16"]
}

resource "alicloud_db_database" "memoria" {
  instance_id    = alicloud_db_instance.postgres.id
  data_base_name = "memoria"
}

resource "alicloud_db_account" "app" {
  db_instance_id   = alicloud_db_instance.postgres.id
  account_name     = "memoria"
  account_password = random_password.db.result
  account_type     = "Super"
}

# -----------------------------------------------------------------------------
# ApsaraDB for Redis (KVStore)
# -----------------------------------------------------------------------------
resource "alicloud_kvstore_instance" "redis" {
  db_instance_name = "memoria-redis"
  instance_class   = "redis.master.small.default"
  engine_version   = "7.0"
  vswitch_id       = alicloud_vswitch.this.id
  zone_id          = data.alicloud_zones.default.zones[0].id
  password         = random_password.redis.result
}

# -----------------------------------------------------------------------------
# Cloud-init: install Docker + Compose plugin and run the backend container,
# wiring DB and Redis URLs from the provisioned resources.
# -----------------------------------------------------------------------------
locals {
  database_url = format(
    "postgresql+asyncpg://%s:%s@%s:%s/%s",
    alicloud_db_account.app.account_name,
    random_password.db.result,
    alicloud_db_instance.postgres.connection_string,
    alicloud_db_instance.postgres.port,
    alicloud_db_database.memoria.data_base_name,
  )

  redis_url = format(
    "redis://:%s@%s:%s/0",
    random_password.redis.result,
    alicloud_kvstore_instance.redis.connection_domain,
    alicloud_kvstore_instance.redis.port,
  )

  user_data = <<-EOT
    #!/bin/bash
    set -euo pipefail

    # 1. Install Docker + Compose plugin.
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker

    # 2. Pull the pre-built backend image from the container registry.
    docker pull ${var.backend_image}

    # 3. Run the FastAPI backend, wiring provisioned DB/Redis + Qwen key.
    docker run -d --restart always --name memoria-backend \
      -p 8000:8000 \
      -e DASHSCOPE_API_KEY='${var.dashscope_api_key}' \
      -e DATABASE_URL='${local.database_url}' \
      -e REDIS_URL='${local.redis_url}' \
      ${var.backend_image}
  EOT
}

# -----------------------------------------------------------------------------
# ECS instance running the app container
# -----------------------------------------------------------------------------
resource "alicloud_instance" "app" {
  instance_name              = "memoria-app"
  image_id                   = data.alicloud_images.ubuntu.images[0].id
  instance_type              = var.ecs_instance_type
  security_groups            = [alicloud_security_group.this.id]
  vswitch_id                 = alicloud_vswitch.this.id
  internet_max_bandwidth_out = 10 # allocate a public IP
  user_data                  = base64encode(local.user_data)

  depends_on = [
    alicloud_db_account.app,
    alicloud_db_database.memoria,
    alicloud_kvstore_instance.redis,
  ]
}

# -----------------------------------------------------------------------------
# Outputs (connection strings; passwords are sensitive)
# -----------------------------------------------------------------------------
output "app_public_ip" {
  description = "Public IP of the app server (FastAPI on :8000)."
  value       = alicloud_instance.app.public_ip
}

output "app_url" {
  description = "Base URL for the deployed backend."
  value       = "http://${alicloud_instance.app.public_ip}:8000"
}

output "database_url" {
  description = "Async PostgreSQL connection string (contains generated password)."
  value       = local.database_url
  sensitive   = true
}

output "redis_url" {
  description = "Redis connection string (contains generated password)."
  value       = local.redis_url
  sensitive   = true
}
